### ISSUE TITLE
Create Class Diagram and Database Design

### ISSUE THREAD

**Issue by andilazvegas** [gunadarma-academy/asde-go-pals#2]

**Comment by fhnbarock** [comment]
Gas Station Table
![cth spbu](https://cloud.githubusercontent.com/assets/17759570/13842529/3b15208c-ec61-11e5-9f71-0652431afe1a.PNG)

ATM Table
![cth atm](https://cloud.githubusercontent.com/assets/17759570/13842531/3b298b58-ec61-11e5-9559-8e38dc2915a0.PNG)

Repair Shop Table
![cth bengkel](https://cloud.githubusercontent.com/assets/17759570/13842530/3b205d9e-ec61-11e5-886b-b0519f968d60.PNG)

**Comment by marvinmarpol** [comment]
![tabel map](https://cloud.githubusercontent.com/assets/4659579/13874562/5a5990de-ed2b-11e5-949d-b9b96ec97ddf.png)

Nitip batagor ndi :japanese_ogre:

**Comment by andilazvegas** [comment]
wakakakak, implementasinye gampang ga tuh le

**Comment by marvinmarpol** [comment]
suruh gopal lah wkwk

**Comment by andilazvegas** [comment]
bentar gw pahamin dulu dah join2an sql

**Comment by fhnbarock** [comment]
![pals class diagram](https://cloud.githubusercontent.com/assets/17759570/13976335/7f174668-f0f1-11e5-80f6-99ffff1c85a7.jpg)
